In [2]:
import numpy as np
import math

L, dk,dv = 4,8,8
q = np.random.randn(L, dk)
k = np.random.rand(L, dk)
v = np.random.rand(L, dv)

In [3]:
q

array([[-0.31133363, -0.87793783, -0.31490595,  2.17640748,  0.3600335 ,
         1.06512027, -0.85942329,  0.37341986],
       [-0.99770687,  0.26922153, -0.55465703, -0.28162611,  1.33060989,
         1.17128111, -0.61062311,  0.10770465],
       [ 0.01200964,  1.84521253, -0.60227995, -0.51196604, -1.91170582,
        -1.32014111,  0.83236064,  0.12071681],
       [ 0.18606656,  1.2195091 , -0.70221978, -0.63373185, -1.2063781 ,
        -0.86902947,  0.38435486,  0.76094921]])

In [4]:
k

array([[0.9808406 , 0.50926205, 0.71224208, 0.31978649, 0.69250348,
        0.61322205, 0.68810579, 0.98649613],
       [0.72899978, 0.87485509, 0.70117927, 0.46789814, 0.3685546 ,
        0.48470362, 0.14961847, 0.30638599],
       [0.17090021, 0.255414  , 0.91462907, 0.37681794, 0.52254827,
        0.9262963 , 0.17388457, 0.69738299],
       [0.18829599, 0.60115719, 0.60818373, 0.12296862, 0.17642633,
        0.50343693, 0.06987171, 0.38229689]])

In [5]:
v

array([[0.77113831, 0.28168928, 0.04169793, 0.70078286, 0.95780301,
        0.13583416, 0.08558999, 0.12378819],
       [0.48576079, 0.11203749, 0.30519042, 0.25840746, 0.76216195,
        0.28749048, 0.5929646 , 0.1550846 ],
       [0.90363364, 0.77547421, 0.33990465, 0.44541323, 0.29290804,
        0.24549456, 0.51608346, 0.93653209],
       [0.82970568, 0.03625615, 0.93122519, 0.53816238, 0.34591903,
        0.10417705, 0.50825013, 0.06667975]])

In [6]:
np.matmul(q, k.T)

array([[ 3.98710151e-01,  4.37285623e-01,  1.54037071e+00,
         1.72155783e-01],
       [-8.13101920e-04, -1.27193089e-02,  1.03402214e+00,
         4.24946366e-01],
       [-1.08277640e+00, -2.21728255e-01, -2.26331503e+00,
        -2.15303387e-01],
       [-2.52436829e-01, -1.61554848e-01, -1.37565680e+00,
        -6.94298722e-02]])

In [7]:
q.var(), k.var(), np.matmul(q, k.T).var()

(0.8847546399085398, 0.07150654420719968, 0.7631445428958854)

In [8]:
scaled = np.matmul(q, k.T)/math.sqrt(dk)
q.var(), k.var(), scaled.var()

(0.8847546399085398, 0.07150654420719968, 0.09539306786198568)

In [9]:
scaled

array([[ 1.40965326e-01,  1.54603815e-01,  5.44603286e-01,
         6.08662608e-02],
       [-2.87474941e-04, -4.49695478e-03,  3.65582033e-01,
         1.50241228e-01],
       [-3.82819269e-01, -7.83927763e-02, -8.00202704e-01,
        -7.61212425e-02],
       [-8.92498967e-02, -5.71182642e-02, -4.86368125e-01,
        -2.45471667e-02]])

In [10]:
#decoder
mask = np.tril(np.ones((L,L)))
mask    

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [11]:
mask[mask==0] = -np.infty
mask[mask==1] = 0


In [12]:
mask

array([[  0., -inf, -inf, -inf],
       [  0.,   0., -inf, -inf],
       [  0.,   0.,   0., -inf],
       [  0.,   0.,   0.,   0.]])

In [13]:
scaled + mask

array([[ 1.40965326e-01,            -inf,            -inf,
                   -inf],
       [-2.87474941e-04, -4.49695478e-03,            -inf,
                   -inf],
       [-3.82819269e-01, -7.83927763e-02, -8.00202704e-01,
                   -inf],
       [-8.92498967e-02, -5.71182642e-02, -4.86368125e-01,
        -2.45471667e-02]])

In [14]:
def softmax(x):
    return (np.exp(x).T/ np.sum(np.exp(x), axis=-1)).T

In [15]:
attention = softmax(scaled + mask)
attention

array([[1.        , 0.        , 0.        , 0.        ],
       [0.50105237, 0.49894763, 0.        , 0.        ],
       [0.33171727, 0.44975792, 0.21852481, 0.        ],
       [0.26512893, 0.2737863 , 0.17823413, 0.28285064]])

In [16]:
new_v = np.matmul(attention, v)
new_v

array([[0.77113831, 0.28168928, 0.04169793, 0.70078286, 0.95780301,
        0.13583416, 0.08558999, 0.12378819],
       [0.62874987, 0.19704192, 0.17316688, 0.4800607 , 0.86018837,
        0.21150272, 0.33874335, 0.13940346],
       [0.67174103, 0.3132913 , 0.22537133, 0.44601642, 0.72451585,
        0.22800631, 0.40785925, 0.3154687 ],
       [0.73318686, 0.25382936, 0.41859253, 0.48815364, 0.61266042,
        0.18794658, 0.42078053, 0.26106226]])

In [17]:
v

array([[0.77113831, 0.28168928, 0.04169793, 0.70078286, 0.95780301,
        0.13583416, 0.08558999, 0.12378819],
       [0.48576079, 0.11203749, 0.30519042, 0.25840746, 0.76216195,
        0.28749048, 0.5929646 , 0.1550846 ],
       [0.90363364, 0.77547421, 0.33990465, 0.44541323, 0.29290804,
        0.24549456, 0.51608346, 0.93653209],
       [0.82970568, 0.03625615, 0.93122519, 0.53816238, 0.34591903,
        0.10417705, 0.50825013, 0.06667975]])

In [18]:
def softmax_function(x):
    return (np.exp(x).T/ np.sum(np.exp(x), axis=-1)).T

def scaled_dot_product_attention(q, k, v, mask=None):
    dk = q.shape[-1]
    scaled = np.matmul(q, k.T)/ math.sqrt(dk)
    if mask is not None:
        scaled = scaled + mask
    attention = softmax(scaled)
    out = np.matmul(attention, v)
    return out, attention    

In [19]:
values, attention = scaled_dot_product_attention(q, k, v, mask=mask)
print("Q", q)  
print('K',k)
print('V', v) 
print('new v', values ) 
print('attention\n', attention)

Q [[-0.31133363 -0.87793783 -0.31490595  2.17640748  0.3600335   1.06512027
  -0.85942329  0.37341986]
 [-0.99770687  0.26922153 -0.55465703 -0.28162611  1.33060989  1.17128111
  -0.61062311  0.10770465]
 [ 0.01200964  1.84521253 -0.60227995 -0.51196604 -1.91170582 -1.32014111
   0.83236064  0.12071681]
 [ 0.18606656  1.2195091  -0.70221978 -0.63373185 -1.2063781  -0.86902947
   0.38435486  0.76094921]]
K [[0.9808406  0.50926205 0.71224208 0.31978649 0.69250348 0.61322205
  0.68810579 0.98649613]
 [0.72899978 0.87485509 0.70117927 0.46789814 0.3685546  0.48470362
  0.14961847 0.30638599]
 [0.17090021 0.255414   0.91462907 0.37681794 0.52254827 0.9262963
  0.17388457 0.69738299]
 [0.18829599 0.60115719 0.60818373 0.12296862 0.17642633 0.50343693
  0.06987171 0.38229689]]
V [[0.77113831 0.28168928 0.04169793 0.70078286 0.95780301 0.13583416
  0.08558999 0.12378819]
 [0.48576079 0.11203749 0.30519042 0.25840746 0.76216195 0.28749048
  0.5929646  0.1550846 ]
 [0.90363364 0.77547421 0.33990